"""Digital Twin fidelity dashboard from reports/digital_twin.json."""
from __future__ import annotations

import json
from pathlib import Path

R = json.loads(Path("reports/digital_twin.json").read_text())
base, cal = R["baseline_fidelity"], R["calibrated_fidelity"]
seg = cal["per_segment_fidelity"]
calib = cal["calibration_curve"]

data = {
    "seg_labels": list(seg.keys()),
    "seg_real": [seg[s]["real_accept_rate"] * 100 for s in seg],
    "seg_sim": [seg[s]["sim_accept_rate"] * 100 for s in seg],
    "calib_pred": [c["predicted"] for c in calib],
    "calib_actual": [c["actual"] for c in calib],
    "fid_labels": ["Uncalibrated", "Calibrated"],
    "fid_vals": [base["composite_fidelity_score"], cal["composite_fidelity_score"]],
}

html = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Digital Twin Fidelity</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<style>
 body{{font-family:'Segoe UI',system-ui,sans-serif;background:#f6f7fb;color:#1c2333;margin:0}}
 header{{background:#141e33;color:#fff;padding:16px 30px}} h1{{font-size:20px;margin:0}}
 .sub{{color:#aab4cc;font-size:13px}}
 main{{max-width:1080px;margin:22px auto;padding:0 18px}}
 .kpis{{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px;margin-bottom:20px}}
 .kpi{{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:16px}}
 .kpi .l{{color:#6b7280;font-size:13px}}.kpi .v{{font-size:24px;font-weight:700;margin-top:4px}}
 .kpi.good .v{{color:#14804a}}
 .grid{{display:grid;grid-template-columns:1fr 1fr;gap:18px}}
 .panel{{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px;margin-bottom:18px}}
 .panel h2{{font-size:15px;margin:0 0 12px}} canvas{{max-height:270px}}
 @media(max-width:800px){{.grid{{grid-template-columns:1fr}}}}
 footer{{color:#6b7280;font-size:12px;text-align:center;margin:24px 0}}
</style></head><body>
<header><h1>Digital Twin — Customer Behavior Simulation Fidelity</h1>
<div class="sub">Synthetic personas · simulated vs real decisions · calibration experiment · what-if</div></header>
<main>
<div class="kpis">
 <div class="kpi good"><div class="l">Composite fidelity</div><div class="v">{cal['composite_fidelity_score']}</div></div>
 <div class="kpi good"><div class="l">Fidelity gain (calibration)</div><div class="v">+{R['fidelity_improvement']}</div></div>
 <div class="kpi"><div class="l">Decision accuracy</div><div class="v">{cal['decision_accuracy']}</div></div>
 <div class="kpi"><div class="l">Twins simulated</div><div class="v">{R['n_twins']:,}</div></div>
</div>
<div class="grid">
 <div class="panel"><h2>Simulated vs real accept rate by segment (%)</h2><canvas id="c1"></canvas></div>
 <div class="panel"><h2>Calibration: predicted vs actual</h2><canvas id="c2"></canvas></div>
</div>
<div class="panel"><h2>Fidelity improvement through experimentation</h2><canvas id="c3"></canvas></div>
</main>
<footer>Synthetic data · generated by src/digital_twin/build_dashboard.py · fidelity = alignment to real outcomes</footer>
<script>
const D={json.dumps(data)};
new Chart(c1,{{type:'bar',data:{{labels:D.seg_labels,datasets:[
 {{label:'Real',data:D.seg_real,backgroundColor:'#141e33'}},
 {{label:'Simulated (twin)',data:D.seg_sim,backgroundColor:'#2ca86b'}}]}}}});
new Chart(c2,{{type:'line',data:{{labels:D.calib_pred,datasets:[
 {{label:'Actual',data:D.calib_actual,borderColor:'#2749c9',tension:.2}},
 {{label:'Ideal',data:D.calib_pred,borderColor:'#b0b0b0',borderDash:[5,5],pointRadius:0}}]}},
 options:{{scales:{{x:{{title:{{display:true,text:'predicted'}}}},y:{{title:{{display:true,text:'actual'}}}}}}}}}});
new Chart(c3,{{type:'bar',data:{{labels:D.fid_labels,datasets:[{{data:D.fid_vals,backgroundColor:['#9aa3b2','#14804a']}}]}},options:{{plugins:{{legend:{{display:false}}}},scales:{{y:{{title:{{display:true,text:'composite fidelity'}}}}}}}}}});
</script></body></html>"""
Path("reports").mkdir(exist_ok=True)
Path("reports/digital_twin_dashboard.html").write_text(html, encoding="utf-8")
print("Dashboard written to reports/digital_twin_dashboard.html")
