"""NBA measurement dashboard from reports/nba_results.json."""
from __future__ import annotations

import json
from pathlib import Path

A = json.loads(Path("reports/nba_results.json").read_text())
meas, summ = A["measurement"], A["nba_summary"]

actions = list(meas.keys())
data = {
    "actions": actions,
    "qini_uplift": [meas[a]["qini_uplift"] for a in actions],
    "qini_prop": [meas[a]["qini_propensity"] for a in actions],
    "ab_lift": [meas[a]["ab_test"]["absolute_lift"] * 100 for a in actions],
    "nba_labels": list(summ["by_action"].keys()),
    "nba_values": list(summ["by_action"].values()),
}

html = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Next Best Action — Measurement</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<style>
 body{{font-family:'Segoe UI',system-ui,sans-serif;background:#f6f7fb;color:#1c2333;margin:0}}
 header{{background:#3b1e6e;color:#fff;padding:16px 30px}} h1{{font-size:20px;margin:0}}
 .sub{{color:#d3c6ee;font-size:13px}}
 main{{max-width:1150px;margin:22px auto;padding:0 18px}}
 .kpis{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:14px;margin-bottom:20px}}
 .kpi{{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:16px}}
 .kpi .l{{color:#6b7280;font-size:13px}}.kpi .v{{font-size:24px;font-weight:700;margin-top:4px}}
 .kpi.good .v{{color:#14804a}}
 .grid{{display:grid;grid-template-columns:1fr 1fr;gap:18px}}
 .panel{{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px;margin-bottom:18px}}
 .panel h2{{font-size:15px;margin:0 0 12px}} canvas{{max-height:270px}}
 @media(max-width:800px){{.grid{{grid-template-columns:1fr}}}}
 footer{{color:#6b7280;font-size:12px;text-align:center;margin:26px 0}}
</style></head><body>
<header><h1>Next Best Action — Measurement & Decisioning</h1>
<div class="sub">Uplift modeling · Qini evaluation · A/B lift · eligibility-constrained NBA</div></header>
<main>
<div class="kpis">
 <div class="kpi good"><div class="l">Members contacted</div><div class="v">{summ['contacted']:,}</div></div>
 <div class="kpi"><div class="l">Suppressed (no +EV action)</div><div class="v">{summ['suppressed']:,}</div></div>
 <div class="kpi good"><div class="l">Total expected value</div><div class="v">{summ['total_expected_value']:,.0f}</div></div>
 <div class="kpi"><div class="l">Actions in play</div><div class="v">{len(summ['by_action'])}</div></div>
</div>
<div class="grid">
 <div class="panel"><h2>Qini: uplift vs propensity targeting (higher = better)</h2><canvas id="c1"></canvas></div>
 <div class="panel"><h2>A/B incremental lift by action (pp)</h2><canvas id="c2"></canvas></div>
</div>
<div class="panel"><h2>Next Best Action allocation (post eligibility + constraints)</h2><canvas id="c3"></canvas></div>
</main>
<footer>Synthetic data · generated by src/build_dashboard.py from reports/nba_results.json</footer>
<script>
const D={json.dumps(data)};
new Chart(c1,{{type:'bar',data:{{labels:D.actions,datasets:[
 {{label:'Uplift targeting',data:D.qini_uplift,backgroundColor:'#3b1e6e'}},
 {{label:'Propensity targeting',data:D.qini_prop,backgroundColor:'#c0aee0'}}]}}}});
new Chart(c2,{{type:'bar',data:{{labels:D.actions,datasets:[{{data:D.ab_lift,backgroundColor:'#14804a'}}]}},options:{{plugins:{{legend:{{display:false}}}},scales:{{y:{{title:{{display:true,text:'lift (pp)'}}}}}}}}}});
new Chart(c3,{{type:'doughnut',data:{{labels:D.nba_labels,datasets:[{{data:D.nba_values,backgroundColor:['#3b1e6e','#2749c9','#14804a']}}]}}}});
</script></body></html>"""

Path("reports").mkdir(exist_ok=True)
Path("reports/dashboard.html").write_text(html, encoding="utf-8")
print("Dashboard written to reports/dashboard.html")
